Added GitHub Actions job to validate the tf script

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -1,4 +1,4 @@
-name: Validate terraform fmt
+name: Validate terraform fmt and validate
 on:
   pull_request:
     branches:
@@ -10,11 +10,11 @@ permissions:
   contents: read
 
 jobs:
-  validate:
+  validate_fmt:
     runs-on: ubuntu-latest
     name: terraform fmt check
     outputs:
-      CHECK_STATUS: "${{ env.CHECK_STATUS }}"
+      CHECK_STATUS: "${ env.CHECK_STATUS }"
     steps:
       - uses: actions/checkout@v3
         with:
@@ -50,3 +50,44 @@ jobs:
       - name: Process check
         if: always()
         run: exit $CHECK_STATUS
+
+  validate_terraform:
+    runs-on: ubuntu-latest
+    name: terraform validate check
+    outputs:
+      VALIDATE_STATUS: "${ env.VALIDATE_STATUS }"
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 2
+      - name: Fetch changed files
+        id: pr_files
+        uses: jitterbit/get-changed-files@v1
+        with:
+          format: "space-delimited"
+      - name: Configure terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.2.4
+      - name: Validate terraform scripts
+        run: |
+          set +e
+
+          echo "VALIDATE_STATUS=0" >> $GITHUB_ENV
+
+          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
+            echo "Validating terraform script ${changed_file}..."
+
+            if [[ $changed_file == *.tf ]]; then
+              terraform validate $changed_file
+              VALIDATE_RESULT=$?
+
+              if [[ $VALIDATE_RESULT -ne 0 ]]; then
+                echo "❌ terraform validate failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
+                echo "VALIDATE_STATUS=1" >> $GITHUB_ENV
+              fi
+            fi
+          done
+      - name: Process check
+        if: always()
+        run: exit $VALIDATE_STATUS
